name       : libfabric
version    : 1.13.2
release    : 1
source     :
    - https://github.com/ofiwg/libfabric/releases/download/v1.13.2/libfabric-1.13.2.tar.bz2 : 25d783b0722a8df8fe61c1de75fafca684c5fe520303180f26f0ad6409cfc0b9
homepage   : https://ofiwg.github.io/libfabric/
license    :
    - BSD-2-Clause
    - GPL-2.0-only
component  : programming.library
summary    : Open Fabric Interfaces 
description: |
    The Open Fabrics Interfaces (OFI) is a framework focused on exporting fabric communication services to applications.
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -f $installdir/usr/lib*/*.a
