name       : libfabric
version    : 1.19.0
release    : 4
source     :
    - https://github.com/ofiwg/libfabric/releases/download/v1.19.0/libfabric-1.19.0.tar.bz2 : f14c764be9103e80c46223bde66e530e5954cb28b3835b57c8e728479603ef9e
homepage   : https://ofiwg.github.io/libfabric/
license    :
    - BSD-2-Clause
    - GPL-2.0-only
component  : programming.library
summary    : Open Fabric Interfaces
description: |
    The Open Fabrics Interfaces (OFI) is a framework focused on exporting fabric communication services to applications.
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -f $installdir/usr/lib*/*.a
